
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/



test:unittest:
  image: python:latest
  tags: 
    - grouprunner
  before_script:
    - python -V  # Print out python version for debugging
    - pip install psycopg2 pytest-coverage beautifultable pyyaml
  script:
    pytest --cov=. *_test.py


test:monetdb:
  image: monetdb/monetdb
  tags:
    - grouprunner
  before_script:
    - python -V  # Print out python version for debugging
    - pip install wheel pyyaml sqlalchemy_monetdb pymonetdb pandas
    - monetdbd start -n /var/monetdb5/dbfarm &
  script:
    python -m grizzly.it.itest nodocker monetdb

test:postgresql:
  image: postgres
  tags:
    - grouprunner
  before_script:
    - apt update
    - apt install -y python3 python3-pip
    - python3 -V  # Print out python version for debugging
    - pip3 install wheel pyyaml psycopg2-binary pandas sqlalchemy
    - /docker-entrypoint.sh postgres &
  script:
    python3 -m grizzly.it.itest nodocker postgresql
