postgresql:
  image: postgres:13
  environment:
    POSTGRES_PASSWORD: example  
  user: postgres
  password: example
  port: 5432
  db: postgres
  container_setup:
    - apt-get update
    - apt-get install  -y postgresql-plpython3-13
    - psql -U postgres -c "create language plpython3u"
    - psql -U postgres -c "CREATE EXTENSION file_fdw"

monetdb:
  image: monetdb/monetdb
  # image: monetdb/monetdb:Jan2022-SP2
  user: monetdb
  password: monetdb
  port: 50000
  db: demo
  container_setup: 
    - rpm --import https://dev.monetdb.org/downloads/MonetDB-GPG-KEY
    - dnf install -y python3 python3-pip MonetDB-python3 python3-numpy
    - pip install wheel pyyaml sqlalchemy_monetdb pymonetdb pandas numpy
    - monetdb create demo
    - monetdb release demo
    # - monetdbd start /var/monetdb5/dbfarm 
    - monetdb set embedpy3=yes demo
    # - monetdb start demo

vector:
  image: actian/vector
  user: actian
  password: actian
  db: testdb
  port:
    - 27832
    - 44223
    - 27839
    - 16902