postgresql:
  image: postgres
  environment:
    POSTGRES_PASSWORD: example  
  user: postgres
  password: example
  port: 5432
  db: postgres
  container_setup:
    - apt-get update
    - apt-get install  -y postgresql-plpython3-13
    - psql -U postgres -c "create language plpython3u"
    - psql -U postgres -c "CREATE EXTENSION file_fdw"

monetdb:
  image: monetdb/monetdb
  user: monetdb
  password: monetdb
  port: 50000
  db: demo
  container_setup: 
    - pip install wheel pyyaml sqlalchemy_monetdb pymonetdb pandas
    - dnf install -y https://www.monetdb.org/downloads/Fedora/33/x86_64/MonetDB-python3-11.39.17-20210503.fc33.x86_64.rpm
    - monetdb set embedpy3=yes demo

vector:
  image: actian/vector
  user: actian
  password: actian
  db: testdb
  port:
    - 27839
    - 27832
    - 44223
    - 16902